// if key == value, it tells `getErrorMessage` to keep the original message
const errors = {
    1001: 'Internal server error',
    1010: 1010,
    1011: 1011,
    1012: 1012,
    1013: 1013,
    1014: 1014,
    1021: 'Nickname already in use',
    1025: 'The given token is invalid',
    1026: 1026,
    1027: 'Invalid credentials',
    1028: 1028,
    1030: 1030,
    1031: 1031,
    1032: 1032,
    1033: 1033,
    1035: 1035,
    1036: 1036,
    1040: 1040,
    1041: 1041,
    1042: 1042,
    1043: 1043,
    1044: 1044,
    1045: 1045,
    1046: 1046,
    1047: 1047,
    1048: 1048,
    1049: 1049,
    1050: 1050,
    1051: 1051,
    1052: 1052,
    1053: 1053,
}

export const getErrorMessage = (error) => {
    // error not generated by api
    if (!(error instanceof Object) || !('code' in error)) {
        console.error(error)
        return 'Unexpected error'
    }

    // if code is not known
    if (!(error.code in errors)) {
        console.error(error)
        return 'Unknown error'
    }

    if (error.code == errors[error.code]) {
        return error.message
    }

    return errors[error.code]
}
